### ISSUE TITLE
stLeaRn availability

### ISSUE THREAD

**Issue by maichanLAU** [sales-lab/stLeaRn#1]
Hi,
I am interested in applying the stLearn method to my ST data, I was wondering if the R wrapper, stLeaRn, will be available on Github soon?
Thanks.

**Comment by davidecrs** [comment]
Hi,

we are not currently working on this wrapper, however if you are interested you can use the spatialDE wrapper that we have recently submitted to bioconductor and is under revision.

https://github.com/sales-lab/spatialDE

Best regards
Davide

**Comment by maichanLAU** [comment]
Noted and Thank you for your reply.

Regards,
Mai Chan

On 7 Jul 2021, at 3:57 PM, Davide Corso ***@***.******@***.***>> wrote:


Hi,

we are not currently working on this wrapper, however if you are interested you can use the spatialDE wrapper that we have recently submitted to bioconductor and is under revision.

https://github.com/sales-lab/spatialDE

Best regards
Davide
